# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cinit <- function(host, port) {
    invisible(.Call(`_rDotNet_cinit`, host, port))
}

cnew <- function(classname, argv) {
    .Call(`_rDotNet_cnew`, classname, argv)
}

ccall_static <- function(classname, method, argv) {
    .Call(`_rDotNet_ccall_static`, classname, method, argv)
}

ccall <- function(obj, method, argv) {
    .Call(`_rDotNet_ccall`, obj, method, argv)
}

cget <- function(obj, property) {
    .Call(`_rDotNet_cget`, obj, property)
}

cset <- function(obj, property, value) {
    invisible(.Call(`_rDotNet_cset`, obj, property, value))
}

cget_indexed <- function(obj, ith) {
    .Call(`_rDotNet_cget_indexed`, obj, ith)
}

