# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_cinit <- function(host, port) {
    invisible(.Call(`_rDotNet_internal_cinit`, host, port))
}

internal_cnew <- function(classname, argv) {
    .Call(`_rDotNet_internal_cnew`, classname, argv)
}

internal_ccall_static <- function(classname, method, argv) {
    .Call(`_rDotNet_internal_ccall_static`, classname, method, argv)
}

internal_ccall <- function(obj, method, argv) {
    .Call(`_rDotNet_internal_ccall`, obj, method, argv)
}

internal_cget <- function(obj, property) {
    .Call(`_rDotNet_internal_cget`, obj, property)
}

internal_cset <- function(obj, property, value) {
    invisible(.Call(`_rDotNet_internal_cset`, obj, property, value))
}

internal_cget_indexed <- function(obj, ith) {
    .Call(`_rDotNet_internal_cget_indexed`, obj, ith)
}

